spring:
  application:
    name: moim

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pro
    username: kks
    password: kks

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    user:
      name: user
      password: 1234
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "abcd"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_code"
              redirect-uris:
                - "http://localhost:8080/api/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://localhost:8080/api"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false


logging:
  include-application-name: false
  level:
    com:
      example:
        moim:
          chat: info
          member: info
          room: info
          schedule: info
  file:
    name: C:\Users\yong\project\log.txt

debug: true
